### ISSUE TITLE
Build package with salsa + aptly

### ISSUE THREAD

**Issue by arthurlutz** [wolfallein/clockworkpi-retroarch#6]
It would be nice to be able to build this fork of retroarch using salsa's infrastructure. https://salsa.debian.org/ is debian's gitlab instance. 

https://salsa.debian.org/salsa-ci-team/pipeline/ has a common pipeline for package testing and building. First step could be to create a project there and add the pipeline. 

https://tracker.debian.org/pkg/retroarch shows info about the current package. 

https://salsa.debian.org/games-team/retroarch seems to be a simple fork, but maybe we could build upon it.

**Comment by wolfallein** [comment]
It would be nice but I think it is not worth it for now.

RetroArch source changes almost every hour. When I was working on it was essential to get the last commit from the source because it was when they enabled Bluetooth support and I wanted it for our build.

Keeping it in a deb package would be perfect but will increase the time we need to have everything done properly. Since this retroarch version didn't get many users (probably just you and me :D) patching the source could be just enough.

BR
